name: Increment Version

on:
  push:
    branches:
      - dev  # Modify this if you're using a different branch

jobs:
  increment_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read current version
        id: read_version
        run: |
          echo "::set-output name=version::$(grep -oP 'versionName "\K[^"]+' app/build.gradle)"

      - name: Increment version
        id: increment_version
        run: |
          current_version=$(echo "${{ steps.read_version.outputs.version }}")
          IFS='.' read -r -a version_parts <<< "$current_version"
          major="${version_parts[0]}"
          minor="${version_parts[1]}"
          new_minor=$((minor + 1))
          new_version="$major.$new_minor.0"
          echo "::set-output name=new_version::$new_version"

      - name: Update build.gradle with new version
        run: |
          new_version="${{ steps.increment_version.outputs.new_version }}"
          sed -i "s/versionName \".*\"/versionName \"$new_version\"/" app/build.gradle

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add app/build.gradle
          git commit -m "Bump version to ${{ steps.increment_version.outputs.new_version }} [skip ci]"
          git push
